### ISSUE TITLE
Name commis not defined 

### ISSUE THREAD

**Issue by KonstantinosX** [bbengfort/commis#12]
```
Traceback (most recent call last):
  File "example-app.py", line 1, in <module>
    from utility import ExampleUtility
  File "/Users/kostasx/Documents/current_workspace/commis/testing/utility.py", line 10, in <module>
    class ExampleUtility(ConsoleProgram):
  File "/Users/kostasx/Documents/current_workspace/commis/testing/utility.py", line 14, in ExampleUtility
    version     = commis.__version__
NameError: name 'commis' is not defined
```

Tried to run example on the README and wouldn't work unless I hardcoded the version in.

**Comment by bbengfort** [comment]
This is an import error; do you have `import commis` somewhere before that line of code? 

Also, technically you're _supposed_ to hardcode a new version in (e.g. put in the version of your utility, not of commis). Do you want to change the README to have just version = "1.0" or something like that?

**Comment by KonstantinosX** [comment]
Yeah I do. Okay, I thought **version** was some sort of static value for every version of the library (?). If I say version = 0.3 it works.

**Comment by bbengfort** [comment]
Right so just to make sure, this is the version definition in your `ExampleUtility` which extends `ConsoleProgram` right? Technically this should be `foo.__version__` as you really want to put the version of _your_ library into the utility.

**Comment by bbengfort** [comment]
Also I added some code at the top of example.py for help in development.
